### ISSUE TITLE
Amber BoP conflict Thaumcraft Amber

### ISSUE THREAD

**Issue by DarkDon** [AllTheMods/ATM3-Remix#307]
## Expected Behavior
9 amber from thaumcraft should turn into amber block from thaumcraft , because Biomes o plenty 
amber block doesnt work with arcane lamp recipe.

## Current Behavior
Amber turns into Amberblock from Biomes o plenty

## Possible Solution
change recipe? ore dictionare thaumcraft recipes with BoP?

**Comment by whatthedrunk** [comment]
This should be fixed in 1.5.3 coming out later today.

**Comment by malcom2073** [comment]
This is still an issue in 1.6.0 on SMP: Thaumcraft amber blocks are not craftable, 9 amber from thaumcraft craft into 1 BoP amber block.
